apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-malice-app
spec:
  replicas: {{ .Values.malice.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-malice-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-malice-app
    spec:
      containers:
      - name: malice-app
        image: "{{ .Values.malice.app.image.repository }}:{{ .Values.malice.app.image.tag }}"
        ports:
        - containerPort: {{ .Values.malice.app.port }}
        env:
        - name: NODE_ENV
          value: development
        - name: VITE_API_BASE_URL
          value: https://api.donottalktomalice.org

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-malice-cdp
spec:
  replicas: {{ .Values.malice.cdp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-malice-cdp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-malice-cdp
    spec:
      containers:
      - name: malice-cdp
        image: "{{ .Values.malice.cdp.image.repository }}:{{ .Values.malice.cdp.image.tag }}"
        ports:
        - containerPort: {{ .Values.malice.cdp.port }}
        env:
        - name: NODE_ENV
          value: development

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-malice-src
spec:
  replicas: {{ .Values.malice.flaskApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-malice-src
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-malice-src
    spec:
      containers:
      - name: malice-src
        image: "{{ .Values.malice.flaskApp.image.repository }}:{{ .Values.malice.flaskApp.image.tag }}"
        ports:
        - containerPort: {{ .Values.malice.flaskApp.port }}
        env:
        - name: COINBASE_API_URL
          value: http://{{ .Release.Name }}-malice-cdp:{{ .Values.malice.cdp.port }}
        - name: FLASK_ENV
          value: development
        - name: FLASK_DEBUG
          value: "true"
        - name: FLASK_APP
          value: server.py
        - name: DB_NAME
          value: {{ .Values.malice.db.name }}
        - name: DB_USER
          value: {{ .Values.malice.db.user }}
        - name: DB_PASSWORD
          value: {{ .Values.malice.db.password }}
        - name: DB_HOST
          value: {{ .Values.malice.db.host }}
        - name: DB_PORT
          value: {{ .Values.malice.db.port }}
