---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-malice-app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "{{ .Values.malice.app.loadBalancer.certificateId }}"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "{{ .Values.malice.app.loadBalancer.hostname }}"
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-malice-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.malice.app.port }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .Values.malice.app.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-malice-cdp
spec:
  selector:
    app: {{ .Release.Name }}-malice-cdp
  ports:
    - protocol: TCP
      port: {{ .Values.malice.cdp.port }}
      targetPort: {{ .Values.malice.cdp.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-malice-flask-app
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "{{ .Values.malice.flaskApp.loadBalancer.certificateId }}"
    service.beta.kubernetes.io/do-loadbalancer-hostname: "{{ .Values.malice.flaskApp.loadBalancer.hostname }}"

spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-malice-src
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.malice.flaskApp.port }}
    - name: https
      protocol: TCP
      port: 443
      targetPort: {{ .Values.malice.flaskApp.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432