malice:
  app:
    replicaCount: 1
    image:
      repository: registry.digitalocean.com/malice/app
      tag: latest
    port: 8080
    loadBalancer:
      certificateId: "c97aa2ae-8e8b-4a08-9a48-9c15a2561f98"
      hostname: "app.donottalktomalice.org"

  cdp:
    replicaCount: 1
    image:
      repository: registry.digitalocean.com/malice/cdp
      tag: latest
    port: 3000

  flaskApp:
    replicaCount: 1
    image:
      repository: registry.digitalocean.com/malice/src
      tag: latest
    port: 5000
    loadBalancer:
      certificateId: "166f9b09-b888-4d49-9e1a-50f4dd13df81"
      hostname: "api.donottalktomalice.org"

  db:
    name: chatbot
    user: malice
    password: "malice"
    host: "malice"
    port: "5432"


loadBalancer:
  id: ""
  sizeUnit: "1"
  disableLetsEncryptDNSRecords: "false"
  protocol: "https"  
  hostname: "app.donottalktomalice.org" 
  redirectHttpToHttps: "true" 
  enableTLS: true 
